" Vim init 2.0
" Plugins
call plug#begin()
	Plug 'tpope/vim-commentary'
	Plug 'tpope/vim-surround'
	Plug 'tmsvg/pear-tree'
	Plug 'preservim/nerdtree'
	Plug 'easymotion/vim-easymotion'
call plug#end()

set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
let mapleader=" "
set nowrap
set relativenumber
set number
set mouse=a
set clipboard+=unnamedplus
set belloff=all
set hidden
set termguicolors
set incsearch
syntax enable
filetype plugin indent on
colorscheme habamax

" Keybindings
inoremap jk <Esc>
nnoremap ; :
" navigate buffers
noremap <S-j> :bnext<CR>
noremap <S-k> :bprevious<CR>
noremap <Tab> :bprevious<CR>
" open ranger file explorer
map <leader>n :NERDTreeToggle<CR> 
" save with Control-S
map <C-s> :w<CR>
" map <leader>s :w<CR>
" quit with Control-q
map <C-q> :q<CR>
map <leader>q :q<CR>

" easy motion
" <Leader>f{char} to move to {char}
map  <Leader>f <Plug>(easymotion-bd-f)
nmap <Leader>f <Plug>(easymotion-overwin-f)

" s{char}{char} to move to {char}{char}
nmap s <Plug>(easymotion-overwin-f2)

" Move to line
map <Leader>L <Plug>(easymotion-bd-jk)
nmap <Leader>L <Plug>(easymotion-overwin-line)

" Move to word
map  <Leader>w <Plug>(easymotion-bd-w)
nmap <Leader>w <Plug>(easymotion-overwin-w)

" move around splits with Alt-arrow
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>
nnoremap <leader>d dd

" Autocomplete
set completeopt=menu,menuone,noselect
inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<Tab>"
